[build]
  publish = "."

[build.environment]
  NETLIFY_DRAWER = "false"
  NETLIFY_COLLABORATIVE_DEPLOY_PREVIEWS = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
