import PDFDocument from 'pdfkit';
import { Response } from 'express';

interface FinancialReportData {
  totalDonations: number;
  totalExpenses: number;
  remainingBalance: number;
  budgetAllocated: number;
  budgetSpent: number;
  budgetRemaining: number;
  donations: Array<{ receiptNumber: string; donorName: string; amount: number; category: string; date: Date }>;
  expenses: Array<{ expenseName: string; category: string; amount: number; vendor?: string; date: Date }>;
  generatedBy: string;
  festivalYear: number;
  dateRangeLabel?: string;
}

export const generateFinancialPDFReport = (res: Response, data: FinancialReportData) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=Financial_Report_Ganesh_Utsav_${data.festivalYear}.pdf`);

  doc.pipe(res);

  // Background Watermark: VIGHNAHARTA PUJA COMMITTEE CONFIDENTIAL
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.06);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('CONFIDENTIAL FINANCIAL AUDIT STATEMENT', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');

  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(`OFFICIAL FINANCIAL REPORT — GANESH UTSAV ${data.festivalYear}`, 55, 78);
  if (data.dateRangeLabel) {
    doc.fillColor('#F4B942').fontSize(10).font('Helvetica-Bold').text(`PERIOD: ${data.dateRangeLabel.toUpperCase()}`, 55, 95);
  }

  doc.moveDown(3);

  // Summary Metrics Box
  doc.fontSize(13).fillColor('#32070B').font('Helvetica-Bold').text('FINANCIAL SUMMARY OVERVIEW', 40, 135);
  doc.strokeColor('#D4A72C').lineWidth(1.5).moveTo(40, 152).lineTo(555, 152).stroke();

  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Generated By: ${data.generatedBy}`, 40, 162);
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}`, 330, 162);

  // 3 Summary Cards
  const cardY = 180;
  
  // Total Donations Card
  doc.roundedRect(40, cardY, 160, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL COLLECTION', 50, cardY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(`Rs. ${data.totalDonations.toLocaleString('en-IN')}`, 50, cardY + 28);

  // Total Expenses Card
  doc.roundedRect(215, cardY, 160, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL EXPENSE', 225, cardY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(`Rs. ${data.totalExpenses.toLocaleString('en-IN')}`, 225, cardY + 28);

  // Net Balance Card
  doc.roundedRect(390, cardY, 165, 60, 8).fill('#32070B').stroke('#F4B942');
  doc.fillColor('#F4B942').fontSize(9).font('Helvetica-Bold').text('NET SURPLUS / BALANCE', 400, cardY + 10);
  doc.fillColor('#FFF7E8').fontSize(15).font('Helvetica-Bold').text(`Rs. ${data.remainingBalance.toLocaleString('en-IN')}`, 400, cardY + 28);

  // Budget Section
  let currentY = 255;
  doc.fontSize(11).fillColor('#32070B').font('Helvetica-Bold').text('FESTIVAL BUDGET & UTILIZATION', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1).moveTo(40, currentY + 14).lineTo(555, currentY + 14).stroke();

  currentY += 22;
  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Allocated Budget: Rs. ${data.budgetAllocated.toLocaleString('en-IN')}`, 40, currentY);
  doc.text(`Spent: Rs. ${data.budgetSpent.toLocaleString('en-IN')}`, 220, currentY);
  doc.text(`Remaining: Rs. ${data.budgetRemaining.toLocaleString('en-IN')}`, 390, currentY);

  // Donations Table Header
  currentY += 35;
  doc.fontSize(11).fillColor('#32070B').font('Helvetica-Bold').text('RECORDED DONATION RECEIPTS (ALL DATES LEDGER)', 40, currentY);
  currentY += 16;

  // Table Header Row
  doc.rect(40, currentY, 515, 20).fill('#5A0F16');
  doc.fillColor('#FFF7E8').fontSize(8.5).font('Helvetica-Bold');
  doc.text('RECEIPT NO', 45, currentY + 5);
  doc.text('DATE', 155, currentY + 5);
  doc.text('DONOR NAME', 230, currentY + 5);
  doc.text('CATEGORY', 380, currentY + 5);
  doc.text('AMOUNT', 470, currentY + 5, { align: 'right' });

  currentY += 20;
  doc.font('Helvetica').fontSize(8.5).fillColor('#2A1710');

  data.donations.forEach((don, idx) => {
    if (currentY > 740) {
      doc.addPage();
      currentY = 40;
      doc.rect(40, currentY, 515, 20).fill('#5A0F16');
      doc.fillColor('#FFF7E8').fontSize(8.5).font('Helvetica-Bold');
      doc.text('RECEIPT NO', 45, currentY + 5);
      doc.text('DATE', 155, currentY + 5);
      doc.text('DONOR NAME', 230, currentY + 5);
      doc.text('CATEGORY', 380, currentY + 5);
      doc.text('AMOUNT', 470, currentY + 5, { align: 'right' });
      currentY += 20;
    }

    const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
    doc.rect(40, currentY, 515, 18).fill(bg);
    doc.fillColor('#2A1710');

    const dateVal = (don as any).rawDate || don.date;
    const dateFormatted = dateVal
      ? new Date(dateVal).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
      : 'N/A';

    doc.text(don.receiptNumber, 45, currentY + 4);
    doc.text(dateFormatted, 155, currentY + 4);
    doc.text(don.donorName.substring(0, 22), 230, currentY + 4);
    doc.text(don.category.substring(0, 16), 380, currentY + 4);
    doc.text(`Rs. ${don.amount.toLocaleString('en-IN')}`, 470, currentY + 4, { align: 'right' });
    currentY += 18;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Audit Document`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};

export const generateDonorStatementPDF = (
  res: Response,
  data: {
    donorName: string;
    phone?: string;
    email?: string;
    totalAmount: number;
    donationCount: number;
    donations: Array<{
      receiptNumber: string;
      amount: number;
      paymentMethod: string;
      category: string;
      transactionId?: string;
      createdAt: Date;
      notes?: string;
    }>;
    generatedBy: string;
    festivalYear: number;
  }
) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  const safeFileName = data.donorName.replace(/[^a-zA-Z0-9]/g, '_');
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=Donor_Statement_${safeFileName}_${data.festivalYear}.pdf`);

  doc.pipe(res);

  // Background Watermark
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.06);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('OFFICIAL DONOR CONTRIBUTION LEDGER', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');
  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(`DONOR CONTRIBUTION STATEMENT — GANESH UTSAV ${data.festivalYear}`, 55, 78);

  let currentY = 135;

  // Donor Details Box
  doc.roundedRect(40, currentY, 515, 80, 8).fill('#FFF7E8').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(14).font('Helvetica-Bold').text(data.donorName, 55, currentY + 12);
  doc.fillColor('#2A1710').fontSize(9).font('Helvetica');
  doc.text(`Phone: ${data.phone || 'N/A'}`, 55, currentY + 34);
  doc.text(`Email: ${data.email || 'N/A'}`, 55, currentY + 48);

  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL CONTRIBUTION', 380, currentY + 14);
  doc.fillColor('#32070B').fontSize(18).font('Helvetica-Bold').text(`Rs. ${data.totalAmount.toLocaleString('en-IN')}`, 380, currentY + 30);
  doc.fillColor('#2A1710').fontSize(9).font('Helvetica').text(`Total Donations: ${data.donationCount} Times`, 380, currentY + 54);

  currentY += 95;

  // Header
  doc.fontSize(12).fillColor('#32070B').font('Helvetica-Bold').text('ALL DATES CONTRIBUTION LEDGER HISTORY', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1).moveTo(40, currentY + 15).lineTo(555, currentY + 15).stroke();
  currentY += 22;

  // Table Header Row
  doc.rect(40, currentY, 515, 20).fill('#5A0F16');
  doc.fillColor('#FFF7E8').fontSize(8.5).font('Helvetica-Bold');
  doc.text('DATE', 45, currentY + 5);
  doc.text('RECEIPT NO', 130, currentY + 5);
  doc.text('CATEGORY', 240, currentY + 5);
  doc.text('MODE / TXN ID', 350, currentY + 5);
  doc.text('AMOUNT', 480, currentY + 5, { align: 'right' });

  currentY += 20;
  doc.font('Helvetica').fontSize(8.5).fillColor('#2A1710');

  data.donations.forEach((don, idx) => {
    const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
    doc.rect(40, currentY, 515, 22).fill(bg);
    doc.fillColor('#2A1710');

    const dateStr = don.createdAt ? new Date(don.createdAt).toLocaleDateString('en-IN') : 'N/A';
    doc.text(dateStr, 45, currentY + 6);
    doc.text(don.receiptNumber, 130, currentY + 6);
    doc.text(don.category.substring(0, 18), 240, currentY + 6);
    doc.text(`${don.paymentMethod} ${don.transactionId ? `(${don.transactionId.substring(0, 10)})` : ''}`, 350, currentY + 6);
    doc.text(`Rs. ${don.amount.toLocaleString('en-IN')}`, 480, currentY + 6, { align: 'right' });

    currentY += 22;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Donor Contribution Statement`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};
