import PDFDocument from 'pdfkit';
import { Response } from 'express';

// Universal Date Formatter Helper (Guaranteed never N/A)
export const formatDateSafe = (raw: any): string => {
  if (!raw) {
    return new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  }
  const d = new Date(raw);
  if (isNaN(d.getTime())) {
    return String(raw);
  }
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

// Month Grouping Helper (e.g. "August 2026")
export const getMonthLabel = (raw: any): string => {
  if (!raw) {
    return new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
  }
  const d = new Date(raw);
  if (isNaN(d.getTime())) {
    return 'Festival Period 2026';
  }
  return d.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });
};

export interface FinancialReportData {
  totalDonations: number;
  totalExpenses: number;
  remainingBalance: number;
  budgetAllocated: number;
  budgetSpent: number;
  budgetRemaining: number;
  donations: Array<{
    receiptNumber: string;
    donorName: string;
    amount: number;
    category: string;
    paymentMethod?: string;
    date?: Date | string;
    createdAt?: Date | string;
    rawDate?: string;
  }>;
  expenses: Array<{
    invoiceNumber?: string;
    expenseName: string;
    category: string;
    amount: number;
    vendor?: string;
    paidBy?: string;
    paymentMethod?: string;
    date?: Date | string;
    createdAt?: Date | string;
  }>;
  generatedBy: string;
  festivalYear: number;
  dateRangeLabel?: string;
}

export const generateFinancialPDFReport = (res: Response, data: FinancialReportData) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=Financial_Report_Ganesh_Utsav_${data.festivalYear}.pdf`
  );

  doc.pipe(res);

  // Background Watermark
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.05);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('OFFICIAL FINANCIAL AUDIT STATEMENT', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');
  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(
    `OFFICIAL FINANCIAL REPORT — GANESH UTSAV ${data.festivalYear}`,
    55,
    78
  );
  if (data.dateRangeLabel) {
    doc.fillColor('#F4B942').fontSize(10).font('Helvetica-Bold').text(
      `AUDIT PERIOD: ${data.dateRangeLabel.toUpperCase()}`,
      55,
      95
    );
  }

  doc.moveDown(3);

  // Summary Metrics Box
  let currentY = 135;
  doc.fontSize(13).fillColor('#32070B').font('Helvetica-Bold').text('FINANCIAL SUMMARY OVERVIEW', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1.5).moveTo(40, currentY + 16).lineTo(555, currentY + 16).stroke();

  currentY += 26;
  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Generated By: ${data.generatedBy}`, 40, currentY);
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}`, 330, currentY);

  currentY += 18;

  // 3 Summary Cards
  // Total Donations Card
  doc.roundedRect(40, currentY, 160, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL COLLECTION', 50, currentY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(
    `Rs. ${data.totalDonations.toLocaleString('en-IN')}`,
    50,
    currentY + 28
  );

  // Total Expenses Card
  doc.roundedRect(215, currentY, 160, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL EXPENSE', 225, currentY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(
    `Rs. ${data.totalExpenses.toLocaleString('en-IN')}`,
    225,
    currentY + 28
  );

  // Net Balance Card
  doc.roundedRect(390, currentY, 165, 60, 8).fill('#32070B').stroke('#F4B942');
  doc.fillColor('#F4B942').fontSize(9).font('Helvetica-Bold').text('NET SURPLUS / BALANCE', 400, currentY + 10);
  doc.fillColor('#FFF7E8').fontSize(15).font('Helvetica-Bold').text(
    `Rs. ${data.remainingBalance.toLocaleString('en-IN')}`,
    400,
    currentY + 28
  );

  currentY += 75;

  // Budget Section
  doc.fontSize(11).fillColor('#32070B').font('Helvetica-Bold').text('FESTIVAL BUDGET & UTILIZATION', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1).moveTo(40, currentY + 14).lineTo(555, currentY + 14).stroke();

  currentY += 22;
  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Allocated Budget: Rs. ${data.budgetAllocated.toLocaleString('en-IN')}`, 40, currentY);
  doc.text(`Spent: Rs. ${data.budgetSpent.toLocaleString('en-IN')}`, 220, currentY);
  doc.text(`Remaining: Rs. ${data.budgetRemaining.toLocaleString('en-IN')}`, 390, currentY);

  currentY += 35;

  // Group donations by Month
  const donationsByMonth: Record<string, typeof data.donations> = {};
  data.donations.forEach((d) => {
    const rawDate = d.createdAt || d.date || d.rawDate;
    const mLabel = getMonthLabel(rawDate);
    if (!donationsByMonth[mLabel]) donationsByMonth[mLabel] = [];
    donationsByMonth[mLabel].push(d);
  });

  const monthKeys = Object.keys(donationsByMonth);

  doc.fontSize(12).fillColor('#32070B').font('Helvetica-Bold').text(
    `MONTH-WISE DONATION RECEIPTS LEDGER (${data.donations.length} RECEIPTS)`,
    40,
    currentY
  );
  currentY += 18;

  if (monthKeys.length === 0) {
    doc.fontSize(9).fillColor('#888888').text('No donation receipts recorded for this period.', 40, currentY);
    currentY += 20;
  }

  monthKeys.forEach((month) => {
    const monthItems = donationsByMonth[month];
    const monthSubtotal = monthItems.reduce((sum, item) => sum + (Number(item.amount) || 0), 0);

    if (currentY > 700) {
      doc.addPage();
      currentY = 40;
    }

    // Month Section Banner
    doc.rect(40, currentY, 515, 22).fill('#240407');
    doc.fillColor('#F4B942').fontSize(9.5).font('Helvetica-Bold');
    doc.text(`✦ MONTH: ${month.toUpperCase()}`, 50, currentY + 6);
    doc.fillColor('#FFF7E8').fontSize(9).font('Helvetica-Bold');
    doc.text(
      `${monthItems.length} Receipts  |  Subtotal: Rs. ${monthSubtotal.toLocaleString('en-IN')}`,
      300,
      currentY + 6,
      { align: 'right' }
    );
    currentY += 24;

    // Table Header Row
    doc.rect(40, currentY, 515, 18).fill('#5A0F16');
    doc.fillColor('#FFF7E8').fontSize(8).font('Helvetica-Bold');
    doc.text('RECEIPT NO', 45, currentY + 5);
    doc.text('DATE', 150, currentY + 5);
    doc.text('DONOR NAME', 225, currentY + 5);
    doc.text('CATEGORY', 360, currentY + 5);
    doc.text('AMOUNT', 475, currentY + 5, { align: 'right' });
    currentY += 18;

    monthItems.forEach((don, idx) => {
      if (currentY > 740) {
        doc.addPage();
        currentY = 40;
        // Re-print Table Header
        doc.rect(40, currentY, 515, 18).fill('#5A0F16');
        doc.fillColor('#FFF7E8').fontSize(8).font('Helvetica-Bold');
        doc.text('RECEIPT NO', 45, currentY + 5);
        doc.text('DATE', 150, currentY + 5);
        doc.text('DONOR NAME', 225, currentY + 5);
        doc.text('CATEGORY', 360, currentY + 5);
        doc.text('AMOUNT', 475, currentY + 5, { align: 'right' });
        currentY += 18;
      }

      const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
      doc.rect(40, currentY, 515, 18).fill(bg);
      doc.fillColor('#2A1710').font('Helvetica').fontSize(8);

      const formattedDate = formatDateSafe(don.createdAt || don.date || don.rawDate);

      doc.text(don.receiptNumber, 45, currentY + 4);
      doc.text(formattedDate, 150, currentY + 4);
      doc.text((don.donorName || 'Devotee').substring(0, 22), 225, currentY + 4);
      doc.text((don.category || 'General').substring(0, 18), 360, currentY + 4);
      doc.text(`Rs. ${Number(don.amount || 0).toLocaleString('en-IN')}`, 475, currentY + 4, { align: 'right' });
      currentY += 18;
    });

    currentY += 12;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Audit Document`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};

export const generateDonorStatementPDF = (
  res: Response,
  data: {
    donorName: string;
    phone?: string;
    email?: string;
    totalAmount: number;
    donationCount: number;
    donations: Array<{
      receiptNumber: string;
      amount: number;
      paymentMethod: string;
      transactionId?: string;
      category: string;
      createdAt?: Date | string;
      date?: Date | string;
      rawDate?: string;
    }>;
    generatedBy: string;
    festivalYear: number;
  }
) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=Donor_Statement_${data.donorName.replace(/[^a-zA-Z0-9]/g, '_')}_${data.festivalYear}.pdf`
  );

  doc.pipe(res);

  // Background Watermark
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.05);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('OFFICIAL DONOR CONTRIBUTION AUDIT', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');
  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(
    `DONOR CONTRIBUTION STATEMENT — GANESH UTSAV ${data.festivalYear}`,
    55,
    78
  );

  let currentY = 135;

  // Donor Details Box
  doc.roundedRect(40, currentY, 515, 80, 8).fill('#FFF7E8').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(14).font('Helvetica-Bold').text(data.donorName, 55, currentY + 12);
  doc.fillColor('#2A1710').fontSize(9).font('Helvetica');
  doc.text(`Phone: ${data.phone || 'N/A'}`, 55, currentY + 34);
  doc.text(`Email: ${data.email || 'N/A'}`, 55, currentY + 48);

  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('TOTAL CONTRIBUTION', 370, currentY + 14);
  doc.fillColor('#32070B').fontSize(18).font('Helvetica-Bold').text(
    `Rs. ${data.totalAmount.toLocaleString('en-IN')}`,
    370,
    currentY + 30
  );
  doc.fillColor('#2A1710').fontSize(9).font('Helvetica').text(
    `Total Transactions: ${data.donationCount} Times`,
    370,
    currentY + 54
  );

  currentY += 95;

  // Group donor transactions by Month
  const donorByMonth: Record<string, typeof data.donations> = {};
  data.donations.forEach((d) => {
    const rawDate = d.createdAt || d.date || d.rawDate;
    const mLabel = getMonthLabel(rawDate);
    if (!donorByMonth[mLabel]) donorByMonth[mLabel] = [];
    donorByMonth[mLabel].push(d);
  });

  doc.fontSize(12).fillColor('#32070B').font('Helvetica-Bold').text(
    'CHRONOLOGICAL CONTRIBUTION LEDGER HISTORY',
    40,
    currentY
  );
  doc.strokeColor('#D4A72C').lineWidth(1).moveTo(40, currentY + 15).lineTo(555, currentY + 15).stroke();
  currentY += 22;

  Object.entries(donorByMonth).forEach(([month, items]) => {
    const monthSubtotal = items.reduce((sum, item) => sum + (Number(item.amount) || 0), 0);

    if (currentY > 700) {
      doc.addPage();
      currentY = 40;
    }

    // Month Header
    doc.rect(40, currentY, 515, 20).fill('#240407');
    doc.fillColor('#F4B942').fontSize(9).font('Helvetica-Bold');
    doc.text(`📅 ${month.toUpperCase()}`, 50, currentY + 5);
    doc.fillColor('#FFF7E8').text(
      `Subtotal: Rs. ${monthSubtotal.toLocaleString('en-IN')}`,
      350,
      currentY + 5,
      { align: 'right' }
    );
    currentY += 22;

    // Table Header Row
    doc.rect(40, currentY, 515, 18).fill('#5A0F16');
    doc.fillColor('#FFF7E8').fontSize(8).font('Helvetica-Bold');
    doc.text('DATE', 45, currentY + 5);
    doc.text('RECEIPT NO', 130, currentY + 5);
    doc.text('CATEGORY', 240, currentY + 5);
    doc.text('MODE / TXN ID', 350, currentY + 5);
    doc.text('AMOUNT', 480, currentY + 5, { align: 'right' });
    currentY += 18;

    items.forEach((don, idx) => {
      if (currentY > 740) {
        doc.addPage();
        currentY = 40;
      }

      const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
      doc.rect(40, currentY, 515, 20).fill(bg);
      doc.fillColor('#2A1710').font('Helvetica').fontSize(8.5);

      const dateStr = formatDateSafe(don.createdAt || don.date || don.rawDate);
      doc.text(dateStr, 45, currentY + 5);
      doc.text(don.receiptNumber, 130, currentY + 5);
      doc.text((don.category || 'General').substring(0, 18), 240, currentY + 5);
      doc.text(
        `${don.paymentMethod || 'UPI'} ${don.transactionId ? `(${don.transactionId.substring(0, 10)})` : ''}`,
        350,
        currentY + 5
      );
      doc.text(`Rs. ${Number(don.amount || 0).toLocaleString('en-IN')}`, 480, currentY + 5, { align: 'right' });

      currentY += 20;
    });

    currentY += 10;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Donor Contribution Statement`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};

export interface ExpensesReportData {
  totalExpenses: number;
  totalInvoices: number;
  expenses: Array<{
    invoiceNumber?: string;
    expenseName: string;
    category: string;
    vendor?: string;
    paidBy?: string;
    paymentMethod?: string;
    amount: number;
    date?: Date | string;
    createdAt?: Date | string;
  }>;
  categoriesSummary?: Array<{ category: string; amount: number; count: number }>;
  generatedBy: string;
  festivalYear: number;
  dateRangeLabel?: string;
}

export const generateExpensesPDFReport = (res: Response, data: ExpensesReportData) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=Expenses_Report_Ganesh_Utsav_${data.festivalYear}.pdf`
  );

  doc.pipe(res);

  // Background Watermark
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.05);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('EXPENSES & VOUCHERS AUDIT', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');
  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(
    `OFFICIAL EXPENSE TRACKER & VOUCHERS AUDIT — GANESH UTSAV ${data.festivalYear}`,
    55,
    78
  );
  if (data.dateRangeLabel) {
    doc.fillColor('#F4B942').fontSize(10).font('Helvetica-Bold').text(
      `PERIOD: ${data.dateRangeLabel.toUpperCase()}`,
      55,
      95
    );
  }

  doc.moveDown(3);

  // Summary Metrics Box
  let currentY = 135;
  doc.fontSize(13).fillColor('#32070B').font('Helvetica-Bold').text('EXPENSE SUMMARY OVERVIEW', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1.5).moveTo(40, currentY + 16).lineTo(555, currentY + 16).stroke();

  currentY += 26;
  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Generated By: ${data.generatedBy}`, 40, currentY);
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}`, 330, currentY);

  currentY += 20;

  // 3 Summary Cards
  doc.roundedRect(40, currentY, 160, 60, 8).fill('#32070B').stroke('#F4B942');
  doc.fillColor('#F4B942').fontSize(9).font('Helvetica-Bold').text('TOTAL OUTGOING EXPENSES', 50, currentY + 10);
  doc.fillColor('#FFF7E8').fontSize(15).font('Helvetica-Bold').text(
    `Rs. ${data.totalExpenses.toLocaleString('en-IN')}`,
    50,
    currentY + 28
  );

  doc.roundedRect(215, currentY, 160, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('RECORDED VOUCHERS', 225, currentY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(
    `${data.totalInvoices} Invoices`,
    225,
    currentY + 28
  );

  const avg = data.totalInvoices > 0 ? Math.round(data.totalExpenses / data.totalInvoices) : 0;
  doc.roundedRect(390, currentY, 165, 60, 8).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(9).font('Helvetica-Bold').text('AVG EXPENSE / VOUCHER', 400, currentY + 10);
  doc.fillColor('#2A1710').fontSize(15).font('Helvetica-Bold').text(
    `Rs. ${avg.toLocaleString('en-IN')}`,
    400,
    currentY + 28
  );

  currentY += 80;

  // Group Expenses by Month
  const expensesByMonth: Record<string, typeof data.expenses> = {};
  data.expenses.forEach((e) => {
    const rawDate = e.date || e.createdAt;
    const mLabel = getMonthLabel(rawDate);
    if (!expensesByMonth[mLabel]) expensesByMonth[mLabel] = [];
    expensesByMonth[mLabel].push(e);
  });

  doc.fontSize(12).fillColor('#32070B').font('Helvetica-Bold').text(
    `MONTH-WISE EXPENSES & VOUCHERS LEDGER (${data.expenses.length} VOUCHERS)`,
    40,
    currentY
  );
  currentY += 18;

  Object.entries(expensesByMonth).forEach(([month, items]) => {
    const monthSubtotal = items.reduce((sum, item) => sum + (Number(item.amount) || 0), 0);

    if (currentY > 700) {
      doc.addPage();
      currentY = 40;
    }

    // Month Section Header
    doc.rect(40, currentY, 515, 22).fill('#240407');
    doc.fillColor('#F4B942').fontSize(9.5).font('Helvetica-Bold');
    doc.text(`✦ MONTH: ${month.toUpperCase()}`, 50, currentY + 6);
    doc.fillColor('#FFF7E8').fontSize(9).font('Helvetica-Bold');
    doc.text(
      `${items.length} Vouchers  |  Subtotal: Rs. ${monthSubtotal.toLocaleString('en-IN')}`,
      300,
      currentY + 6,
      { align: 'right' }
    );
    currentY += 24;

    // Table Header Row
    doc.rect(40, currentY, 515, 18).fill('#5A0F16');
    doc.fillColor('#FFF7E8').fontSize(8).font('Helvetica-Bold');
    doc.text('INV #', 45, currentY + 5);
    doc.text('DATE', 120, currentY + 5);
    doc.text('DESCRIPTION', 190, currentY + 5);
    doc.text('CATEGORY', 330, currentY + 5);
    doc.text('VENDOR', 420, currentY + 5);
    doc.text('AMOUNT', 485, currentY + 5, { align: 'right' });
    currentY += 18;

    items.forEach((exp, idx) => {
      if (currentY > 740) {
        doc.addPage();
        currentY = 40;
        doc.rect(40, currentY, 515, 18).fill('#5A0F16');
        doc.fillColor('#FFF7E8').fontSize(8).font('Helvetica-Bold');
        doc.text('INV #', 45, currentY + 5);
        doc.text('DATE', 120, currentY + 5);
        doc.text('DESCRIPTION', 190, currentY + 5);
        doc.text('CATEGORY', 330, currentY + 5);
        doc.text('VENDOR', 420, currentY + 5);
        doc.text('AMOUNT', 485, currentY + 5, { align: 'right' });
        currentY += 18;
      }

      const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
      doc.rect(40, currentY, 515, 18).fill(bg);
      doc.fillColor('#2A1710').font('Helvetica').fontSize(8);

      const formattedDate = formatDateSafe(exp.date || exp.createdAt);

      doc.text(exp.invoiceNumber || `INV-${idx + 1}`, 45, currentY + 4);
      doc.text(formattedDate, 120, currentY + 4);
      doc.text((exp.expenseName || '').substring(0, 22), 190, currentY + 4);
      doc.text((exp.category || '').substring(0, 15), 330, currentY + 4);
      doc.text((exp.vendor || 'N/A').substring(0, 12), 420, currentY + 4);
      doc.text(`Rs. ${Number(exp.amount || 0).toLocaleString('en-IN')}`, 485, currentY + 4, { align: 'right' });
      currentY += 18;
    });

    currentY += 12;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Expense Audit Statement`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};

export interface BudgetVarianceReportData {
  totalAllocated: number;
  totalSpent: number;
  totalRemaining: number;
  overallPercentage: number;
  categories: Array<{
    category: string;
    allocated: number;
    spent: number;
    remaining: number;
    percentageUsed: number;
  }>;
  generatedBy: string;
  festivalYear: number;
}

export const generateBudgetVariancePDFReport = (res: Response, data: BudgetVarianceReportData) => {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=Budget_vs_Actual_Variance_${data.festivalYear}.pdf`
  );

  doc.pipe(res);

  // Background Watermark
  doc.save();
  doc.rotate(-30, { origin: [300, 400] });
  doc.fontSize(36);
  doc.fillColor('#5A0F16');
  doc.opacity(0.05);
  doc.text('VIGHNAHARTA PUJA COMMITTEE', 50, 350, { align: 'center' });
  doc.text('BUDGET VS ACTUAL VARIANCE AUDIT', 50, 400, { align: 'center' });
  doc.restore();

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#32070B');
  doc.fillColor('#F4B942').fontSize(20).font('Helvetica-Bold').text('VIGHNAHARTA PUJA COMMITTEE', 55, 52);
  doc.fillColor('#FFF7E8').fontSize(11).font('Helvetica').text(
    `FESTIVAL BUDGET VS ACTUAL VARIANCE AUDIT — GANESH UTSAV ${data.festivalYear}`,
    55,
    78
  );
  doc.fillColor('#F4B942').fontSize(10).font('Helvetica-Bold').text(
    `ANNUAL OPERATIONAL VARIANCE REPORT`,
    55,
    95
  );

  let currentY = 135;
  doc.fontSize(13).fillColor('#32070B').font('Helvetica-Bold').text('BUDGET ALLOCATION & SPENDING OVERVIEW', 40, currentY);
  doc.strokeColor('#D4A72C').lineWidth(1.5).moveTo(40, currentY + 16).lineTo(555, currentY + 16).stroke();

  currentY += 26;
  doc.fontSize(9).fillColor('#2A1710').font('Helvetica');
  doc.text(`Generated By: ${data.generatedBy}`, 40, currentY);
  doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}`, 330, currentY);

  currentY += 20;

  // 4 Top Cards
  doc.roundedRect(40, currentY, 120, 55, 6).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(8).font('Helvetica-Bold').text('TOTAL ALLOCATED', 48, currentY + 8);
  doc.fillColor('#2A1710').fontSize(12).font('Helvetica-Bold').text(
    `Rs. ${data.totalAllocated.toLocaleString('en-IN')}`,
    48,
    currentY + 24
  );

  doc.roundedRect(170, currentY, 120, 55, 6).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(8).font('Helvetica-Bold').text('ACTUAL SPENT', 178, currentY + 8);
  doc.fillColor('#2A1710').fontSize(12).font('Helvetica-Bold').text(
    `Rs. ${data.totalSpent.toLocaleString('en-IN')}`,
    178,
    currentY + 24
  );

  doc.roundedRect(300, currentY, 120, 55, 6).fill('#FBE9CE').stroke('#D4A72C');
  doc.fillColor('#5A0F16').fontSize(8).font('Helvetica-Bold').text('UNSPENT BALANCE', 308, currentY + 8);
  doc.fillColor('#2A1710').fontSize(12).font('Helvetica-Bold').text(
    `Rs. ${data.totalRemaining.toLocaleString('en-IN')}`,
    308,
    currentY + 24
  );

  doc.roundedRect(430, currentY, 125, 55, 6).fill('#32070B').stroke('#F4B942');
  doc.fillColor('#F4B942').fontSize(8).font('Helvetica-Bold').text('UTILIZATION %', 438, currentY + 8);
  doc.fillColor('#FFF7E8').fontSize(14).font('Helvetica-Bold').text(
    `${data.overallPercentage}% Used`,
    438,
    currentY + 24
  );

  currentY += 75;

  // Table
  doc.fontSize(11).fillColor('#32070B').font('Helvetica-Bold').text('BUDGET HEAD VARIANCE BREAKDOWN', 40, currentY);
  currentY += 16;

  doc.rect(40, currentY, 515, 20).fill('#5A0F16');
  doc.fillColor('#FFF7E8').fontSize(8.5).font('Helvetica-Bold');
  doc.text('BUDGET HEAD', 45, currentY + 5);
  doc.text('ALLOCATED (RS.)', 200, currentY + 5, { align: 'right' });
  doc.text('SPENT (RS.)', 290, currentY + 5, { align: 'right' });
  doc.text('VARIANCE (RS.)', 385, currentY + 5, { align: 'right' });
  doc.text('UTIL %', 445, currentY + 5, { align: 'right' });
  doc.text('STATUS', 500, currentY + 5, { align: 'center' });

  currentY += 20;
  doc.font('Helvetica').fontSize(8.5).fillColor('#2A1710');

  data.categories.forEach((cat, idx) => {
    if (currentY > 740) {
      doc.addPage();
      currentY = 40;
      doc.rect(40, currentY, 515, 20).fill('#5A0F16');
      doc.fillColor('#FFF7E8').fontSize(8.5).font('Helvetica-Bold');
      doc.text('BUDGET HEAD', 45, currentY + 5);
      doc.text('ALLOCATED (RS.)', 200, currentY + 5, { align: 'right' });
      doc.text('SPENT (RS.)', 290, currentY + 5, { align: 'right' });
      doc.text('VARIANCE (RS.)', 385, currentY + 5, { align: 'right' });
      doc.text('UTIL %', 445, currentY + 5, { align: 'right' });
      doc.text('STATUS', 500, currentY + 5, { align: 'center' });
      currentY += 20;
    }

    const bg = idx % 2 === 0 ? '#FFFFFF' : '#FFF7E8';
    doc.rect(40, currentY, 515, 20).fill(bg);

    const isOver = cat.percentageUsed > 100;
    const isHigh = cat.percentageUsed >= 85 && cat.percentageUsed <= 100;
    const statusLabel = isOver ? 'OVER' : isHigh ? 'HIGH' : 'ON TRACK';
    const statusColor = isOver ? '#DC2626' : isHigh ? '#D97706' : '#16A34A';

    doc.fillColor('#2A1710');
    doc.text(cat.category.substring(0, 24), 45, currentY + 5);
    doc.text(cat.allocated.toLocaleString('en-IN'), 200, currentY + 5, { align: 'right' });
    doc.text(cat.spent.toLocaleString('en-IN'), 290, currentY + 5, { align: 'right' });
    doc.text(cat.remaining.toLocaleString('en-IN'), 385, currentY + 5, { align: 'right' });
    doc.text(`${cat.percentageUsed}%`, 445, currentY + 5, { align: 'right' });

    doc.fillColor(statusColor).font('Helvetica-Bold');
    doc.text(statusLabel, 500, currentY + 5, { align: 'center' });
    doc.font('Helvetica');

    currentY += 20;
  });

  // Footer Branding
  doc.fontSize(8).fillColor('#888888').text(
    `Vighnaharta Puja Committee © ${data.festivalYear} — Official Budget vs Actual Audit Statement`,
    40,
    780,
    { align: 'center' }
  );

  doc.end();
};
